### PR TITLE
Fixed compilation errors

### PR DESCRIPTION
**Pull request by Lyptik**
Hello,

There is only a few lines changed. for some reasons, github did not do the diff correctly.

Be carefull I think I did undo your 0.9.0 commit in this PR, so pick up only what you need !

### CODE REVIEW

**Comment by elliotwoods** [comment]
ah i see. this issue is likely already fixed on the 0.9.0 (master) branch (explains why you're seeing issues i thought had already been removed)
one possibility is make the PR against the 0.8.4 branch (you can select that when you're making the PR but not afterwards
image


any other changes which you want me to consider? (i.e. to bring into 0.9.0)

**Comment by Lyptik** [comment]
Hello Elliot, thanks, nope, just some compilation errors. I don't see any 0.8.4 branch, but just a tag on the master branch.

I only see jordi, mappingdev, master, master64, static-lib

**Comment by elliotwoods** [comment]
Hi Lyptik

Are you still using 0.8.4? if so i'll make 0.8.4 into a branch and manually pull your commits into that branch

**Comment by Lyptik** [comment]
Hello Elliot,

Yep I will be using of 9 once it’s officially out. I’m using my fork so that’s ok, but a branch would be nice for the other folks around :)

**Comment by elliotwoods** [comment]
To note, there are some tags for different oF versions now. I'm also working on the 0.10.0 version but needs testing
